# Font configuration > kitty list-fonts
font_family IosevkaTerm NF
bold_font IosevkaTerm NF Bold
italic_font auto
bold_italic_font auto

font_size 15
disable_ligatures always

text_composition_strategy legacy

sync_to_monitor no
enable_audio_bell no
cursor_shape block
shell_integration enabled no-cursor

hide_window_decorations yes

# background #1e1e24
# background #1F1F28
# background #181818
# background #19181C
# background #191919
# background #1d2021
# background #14151B
background #141516

map ctrl+shift+r load_config_file
map ctrl+shift+q noop
map ctrl+shift+w noop

map ctrl+v paste_from_clipboard
map ctrl+shift+c copy_to_clipboard

map ctrl+equal change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 15

map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5

